name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configurar Java 21
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3. Rodar os testes do Maven
      - name: Run tests
        working-directory: ./   # ajuste se seu pom.xml estiver em subpasta
        run: mvn test

      # 4. Logar no DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build e push da imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .             # ajuste se o Dockerfile/pom.xml estiver em subpasta
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/calculadora-api:latest
